DROP TABLE IF EXISTS webhook_deliveries;
DROP INDEX IF EXISTS idx_webhook_deliveries_due;
DROP INDEX IF EXISTS idx_email_events_email_timestamp;
DROP INDEX IF EXISTS idx_inbound_emails_team_created_at;
DROP INDEX IF EXISTS idx_contacts_team_created_at;
DROP INDEX IF EXISTS idx_emails_team_created_at;
DROP INDEX IF EXISTS ux_api_keys_key_hash;
DROP INDEX IF EXISTS ux_domains_normalized_name;
DROP INDEX IF EXISTS ux_inbound_emails_team_message_id;
DROP INDEX IF EXISTS ux_emails_team_idempotency_key;
DROP INDEX IF EXISTS ux_emails_provider_message_id;
ALTER TABLE team_members ALTER COLUMN team_id DROP NOT NULL;
ALTER TABLE api_keys ALTER COLUMN team_id DROP NOT NULL;
ALTER TABLE domains ALTER COLUMN team_id DROP NOT NULL;
ALTER TABLE emails ALTER COLUMN team_id DROP NOT NULL;
ALTER TABLE inbound_emails ALTER COLUMN team_id DROP NOT NULL;
ALTER TABLE webhooks ALTER COLUMN team_id DROP NOT NULL;
ALTER TABLE emails DROP COLUMN IF EXISTS provider_message_id;
ALTER TABLE emails DROP COLUMN IF EXISTS sending_at;
ALTER TABLE emails DROP COLUMN IF EXISTS idempotency_hash;
ALTER TABLE emails DROP COLUMN IF EXISTS idempotency_key;
